version: '3.8'

services:

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      SUPABASE_URL: https://project.supabase.co
      SUPABASE_KEY: your-anon-key
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: http://localhost:3000
      JWT_SECRET: production-secret-change-this
      NODE_ENV: production
      PORT: 3001
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
      NEXT_PUBLIC_SOLANA_NETWORK: mainnet-beta
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data:
