version: '3.8'

services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    image: node:20
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    command: bash -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - SUPABASE_URL=https://project.supabase.co
      - SUPABASE_KEY=your-anon-key
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:3000
      - JWT_SECRET=development-secret-key-change-in-production-32chars
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  frontend:
    image: node:20
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}"
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
      - NEXT_PUBLIC_SOLANA_NETWORK=mainnet-beta
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data:
